### ISSUE TITLE
Infinite $digest()

### ISSUE THREAD

**Issue by nedSaf** [shoov/shoov#105]
In my local (master branch) when installed Shoov and added the config files, after logging I have `digest` error on the dashboard.

![localhost_9000__code_7a0d8e4b90dadbfc3284__](https://cloud.githubusercontent.com/assets/7369740/8669167/e13bf2b0-2a1a-11e5-8902-b3573561b534.png)

**Comment by amitaibu** [comment]
I have a feeling it might be related to Pusher
