### ISSUE TITLE
Add "create repo" permission to profile

### ISSUE THREAD

**Issue by amitaibu** [shoov/shoov#12]
in `shoov.profile` the create repository permission is missing from auth users.

**Comment by solker** [comment]
Is it also actually for Screenshots because user upload it?

**Comment by amitaibu** [comment]
Permissions are [here](https://github.com/shoov/shoov/blob/master/shoov/shoov.install#L168-L180) but it's too early. Move to `shoov.profile`, and change so create is given only to `repository` content type.

**Comment by amitaibu** [comment]
@HelenaEksler extra karma points for Behat test :)

**Comment by HelenaEksler** [comment]
@amitaibu 

> and change so create is given only to repository content type.

Do you mean that for all content type permissions should be only `view` and only for content type `repository` permissions should be `create/edit(own)/view/delete(own)`?

**Comment by amitaibu** [comment]
Just remove other content types completely -- OG will take care of them.
