### ISSUE TITLE
pusher_auth is called multiple times

### ISSUE THREAD

**Issue by amitaibu** [shoov/shoov#143]
![https___app_shoov_io___my-account](https://cloud.githubusercontent.com/assets/125707/8847201/2c402314-3135-11e5-837c-d55c4eb31d02.jpg)

**Comment by HelenaEksler** [comment]
@amitaibu Can you write on which page this happens?

**Comment by HelenaEksler** [comment]
On my account page I see 1 OPTIONS request and 4 POST (I have 3 repos enabled and 1 own channel). And each time you are getting data from backend, not from cache - user is subscribed to all channels again.

**Comment by HelenaEksler** [comment]
Is it still relevant?

**Comment by amitaibu** [comment]
Let's keep open. I think we end up with multiple connections per user, instead of multiple channels. Let's discuss later

**Comment by amitaibu** [comment]
We've hit our plan's limit in Pusher yesterday, so this is definitely an issue that needs to be tackled.

**Comment by HelenaEksler** [comment]
@amitaibu I've created test application in Pusher for development in order not to use the main one, and I've sent you and @nader77  invitation to it.
