### ISSUE TITLE
Add trigger now link to CI build items

### ISSUE THREAD

**Issue by amitaibu** [shoov/shoov#154]
Clicking on link will send CI build items to nodejs server

<img width="628" alt="gizra_drupal_org-shoov___shoov" src="https://cloud.githubusercontent.com/assets/125707/8895472/bd28af48-33e4-11e5-9e1c-94f7f5cae3bd.png">

**Comment by HelenaEksler** [comment]
https://github.com/shoov/shoov/blob/master/shoov/modules/custom/shoov_ci_build/drush/shoov_ci_build.drush.inc#L42-L55

**Comment by HelenaEksler** [comment]
- hook_menu
- Views handler to add the "Process now" link

clicking on the link will send that item to nodejs server
