### ISSUE TITLE
Fix status and add pager to CI build items

### ISSUE THREAD

**Issue by amitaibu** [shoov/shoov#163]
From the CI build page

![gizra_imanimo-shoov___shoov](https://cloud.githubusercontent.com/assets/125707/8906707/59a8f398-3479-11e5-8b7e-3bd69e714a4d.jpg)

**Comment by HelenaEksler** [comment]
@amitaibu Do you mean remove filtering by status opportunity?

**Comment by amitaibu** [comment]
No, I mean to keep it - but make it work :)
