### ISSUE TITLE
Validate CI incident title is unique

### ISSUE THREAD

**Issue by amitaibu** [shoov/shoov#171]
<img width="1106" alt="https___app_shoov_io___repos_5373" src="https://cloud.githubusercontent.com/assets/125707/8914240/bff3daaa-34a6-11e5-820d-1a24f3981cc2.png">

**Comment by HelenaEksler** [comment]
I'll also deal with https://github.com/shoov/shoov/pull/140#issuecomment-125293265 here.

**Comment by amitaibu** [comment]
Better separate PRs.

**Comment by amitaibu** [comment]
@HelenaEksler let's discuss tomorrow.

<img width="977" alt="https___app_shoov_io___repos_4586" src="https://cloud.githubusercontent.com/assets/125707/8938661/a6ebbbbe-3568-11e5-8e5e-6da811f92509.png">

**Comment by amitaibu** [comment]
This is probably related to access - so maybe need to add `->addTag('DANGEROUS_ACCESS_CHECK_OPT_OUT')` on the query that gets recent incidetns
