### ISSUE TITLE
Convert UI builds list to table

### ISSUE THREAD

**Issue by amitaibu** [shoov/shoov#172]
Add select list on top to Allow filtering by repo.
Make sure that Pusher continues to work properly even when filtered.

<img width="1137" alt="https___app_shoov_io___builds" src="https://cloud.githubusercontent.com/assets/125707/8914353/6ec1c0b0-34a7-11e5-9a04-258cd101db41.png">

**Comment by nedSaf** [comment]
Table (Label, Repo, Branch, Created, PR link with status) anything else you think should be there ?

**Comment by amitaibu** [comment]
no PR link for now.
