### ISSUE TITLE
Add favicon to the client

### ISSUE THREAD

**Issue by amitaibu** [shoov/shoov#178]

**Comment by nedSaf** [comment]
@amitaibu Do we have a logo ?

**Comment by amitaibu** [comment]
not yet :)

**Comment by nedSaf** [comment]
@amitaibu What do you think about this pattern as a favicon ? (Maybe change the colors because they look like Pepsi :) Maybe put a page in the middle ? )
![orit](https://cloud.githubusercontent.com/assets/7369740/9106373/8026241c-3c28-11e5-8fe8-7e86e9658cda.png)

**Comment by nedSaf** [comment]
@YaronMiro You have a favicon with the new design ?

**Comment by YaronMiro** [comment]
I'm closing this issue it's deprecated. the Shoov has it's own favicon since the new design.
