### ISSUE TITLE
Error in Organizations

### ISSUE THREAD

**Issue by nedSaf** [shoov/shoov#180]
I get "null" in some organizations.
![https___app_shoov_io___repos](https://cloud.githubusercontent.com/assets/7369740/8926992/f6f8f55a-351c-11e5-9340-6621b7223c50.png)

**Comment by amitaibu** [comment]
https://github.com/shoov/shoov/blob/master/client/app/views/login.html#L6

Add `read:org` and try to login with public repos.

**Comment by amitaibu** [comment]
Deployed
