### ISSUE TITLE
Encrypt value is always the same

### ISSUE THREAD

**Issue by amitaibu** [shoov/shoov#196]
No matter the key or value

![https___app_shoov_io___repos_2580_encrypt](https://cloud.githubusercontent.com/assets/125707/8980694/4251684e-36bb-11e5-80de-cfe0e62da23c.jpg)

**Comment by HelenaEksler** [comment]
@amitaibu Can't reproduce locally.

![encrypt](https://cloud.githubusercontent.com/assets/8306902/8981522/bc8a576e-36c1-11e5-9d54-a19b61d3b4d8.gif)

**Comment by amitaibu** [comment]
Update; Issue seems to be related to Pantheon. The key & value aren't sent to the nodejs server
