### ISSUE TITLE
Send email to admin when CI build item queued 3 times [2h]

### ISSUE THREAD

**Issue by amitaibu** [shoov/shoov#213]
Follow up on #210 

The reason is that if an item is re-queued several times it is an indication the Docker container wasn't started properly

**Comment by Moo64c** [comment]
@amitaibu Do we want to send only to the admin (group creator) or to all the subscribed users?

**Comment by amitaibu** [comment]
Not to group creator - to the site admin.

**Comment by Moo64c** [comment]
Ok.
