### ISSUE TITLE
After clicking on Trigger, text should change

### ISSUE THREAD

**Issue by amitaibu** [shoov/shoov#215]
So one cannot re-click on the same link

(Follow up on #154)

**Comment by HelenaEksler** [comment]
Do you mean change the html using Javascript (on click)? Actually, as I understand after triggering status should be changed to "in process" and after reloading page link will become a text.

**Comment by amitaibu** [comment]
> Do you mean change the html using Javascript (on click)?

no, the ajax response should return the new text. Check the ctools_ajax_example

**Comment by HelenaEksler** [comment]
I can't return new text, because the link is not in the form. But I can change the text with javascript or with css (ajax adds class to the link when it's processed). What is better?

**Comment by amitaibu** [comment]
You should be able to use [replace](https://api.drupal.org/api/drupal/includes%21ajax.inc/function/ajax_command_replace/7), no?

**Comment by amitaibu** [comment]
[post](http://www.gizra.com/content/views-and-panels-ajaxified/) I wrote very long time ago (still Drupal 6), but in the exported module you can see the idea:

``` php
    ctools_include('ajax');

    $commands = array();
    // Replace the existing View with the new output.
    $commands[] = ctools_ajax_command_replace('.ajax-result-pane > *', $output);

    ctools_ajax_render($commands);
```
