### ISSUE TITLE
Drush command to check health of server

### ISSUE THREAD

**Issue by amitaibu** [shoov/shoov#229]
It should iterate all nodejs servers and get a 200 response, otherwise, send email to admin

**Comment by HelenaEksler** [comment]
`drush check-nodejs-health`

https://github.com/shoov/shoov/blob/master/shoov/modules/custom/shoov_ci_build/shoov_ci_build.module#L450

**Comment by amitaibu** [comment]
correct command is : `drush check-nodejs-server-health`
