### ISSUE TITLE
If there's no .shoov.yml disable CI build

### ISSUE THREAD

**Issue by amitaibu** [shoov/shoov#269]
And send email with explanation that CI build was disabled, with link to Shoov' tutorial (I'll write a chapter about live monitoring)

**Comment by amitaibu** [comment]
Also, lets add a select field (field_disable_reason on CI build) with the following options:

```
none|None
no_config_file|No .shoov.yml file
```

**Comment by amitaibu** [comment]
@HelenaEksler this seems to not be working for CI builds that were already enabled (see message 112312 for example) - can you please check.

**Comment by HelenaEksler** [comment]
@amitaibu I've added missing html (seems like it was lost when merged master).

Regarding already enabled builds - I can add check when build item status is turned to "error" - also check .shoov.yml file exists and if not - set ci_build node to disabled.

**Comment by amitaibu** [comment]
> Regarding already enabled builds - I can add check when build item status is turned to "error"

Never mind for now, thanks.
