### ISSUE TITLE
consider creating a script for importing the shoov.yml repo?

### ISSUE THREAD

**Issue by niryariv** [shoov/shoov#27]
if i understand correctly, we basically need to copy everything from this repo, but not necessarily fork or clone it (ie, the user won't need to keep it updated)?

if so, perhaps can create a script that downloads everything as a zip, unzips and cleans up and have it running with something like `curl http://shoov.io/installer | sh` or similar

**Comment by amitaibu** [comment]
https://github.com/shoov/generator-shoov
