### ISSUE TITLE
FIx Image position and title font size

### ISSUE THREAD

**Issue by mldk-tech** [shoov/shoov#299]
@amitaibu / @YaronMiro : You can increase the text of the title to 18px?
- [x] Change font size.
  ![shoov](https://cloud.githubusercontent.com/assets/5812423/11062672/70946fa4-87b9-11e5-8573-83da0ad87c4f.png)

**Comment by YaronMiro** [comment]
- [x] Fix image gap  when changing into `diff` image.

**Comment by amitaibu** [comment]
Deployed
