### ISSUE TITLE
Duplicate images are still present

### ISSUE THREAD

**Issue by amitaibu** [shoov/shoov#317]
I've noticed a lot of duplicates in this page (after running the script to dedup them)

@HelenaEksler Can you please check https://app.shoov.io/#/screenshots/6942

**Comment by HelenaEksler** [comment]
I don't have access to this page.
![selection_051](https://cloud.githubusercontent.com/assets/8306902/11612865/8b6d04bc-9c13-11e5-89da-5aa82625239b.png)

**Comment by amitaibu** [comment]
I know, but you have it locally I think?

**Comment by HelenaEksler** [comment]
it takes me about 20-30 minutes to upload images and DB dump. Wanted just to look first at images. Maybe they are not duplicated, maybe there are some small differences.

**Comment by amitaibu** [comment]
Done.

**Comment by HelenaEksler** [comment]
Ok, will check again

**Comment by HelenaEksler** [comment]
Seems like screenshots are not identical.
