### ISSUE TITLE
I get a error when I try to add a project to the live monitor

### ISSUE THREAD

**Issue by mldk-tech** [shoov/shoov#319]
I get a error: `No .shoov.yml file.` ,and I have it in the project.
And the error fome the console: `{"type":"http:\/\/www.w3.org\/Protocols\/rfc2616\/rfc2616-sec10.html#sec10.4.2","title":"Bad credentials","status":401,"detail":"Unauthorized."}`

**Comment by amitaibu** [comment]
@HelenaEksler can you please confirm

**Comment by HelenaEksler** [comment]
@DavidKohav Please, try after @amitaibu deploy the last fix. If problem still exist - let me know.

**Comment by amitaibu** [comment]
Code was deployed, please check in 1 min.

**Comment by mldk-tech** [comment]
:+1:

**Comment by mldk-tech** [comment]
I checked it and this is not solved, can you check it again?

**Comment by HelenaEksler** [comment]
The problem is because repository has been renamed. In backend repository name is "Gizra-Shoov/huji-registration-shoov" and now its name is "Gizra-Shoov/huji-registration-visual" - so Shoov is looking for .shoov.yml file in the "Gizra-Shoov/huji-registration-shoov" repository, which doesn't exist.

**Comment by HelenaEksler** [comment]
@amitaibu Now we can simply rename the repository in the backend. But probably we should handle such situations in future somehow.

**Comment by amitaibu** [comment]
@DavidKohav can you please test again.

**Comment by mldk-tech** [comment]
Looking good, 10x
