### ISSUE TITLE
Bad time format for a field Start Time.

### ISSUE THREAD

**Issue by solker** [shoov/shoov#32]
This format is bad because JS `new Date()` and php `strtotime()` can't parse it. May be get problem in future. 

![selection_053](https://cloud.githubusercontent.com/assets/10127295/7980975/826ec602-0ab4-11e5-8451-2e6130845820.png)

**Comment by amitaibu** [comment]
Internally it's `Date (Unix timestamp)`

**Comment by amitaibu** [comment]
![ci_build___shoov](https://cloud.githubusercontent.com/assets/125707/7981515/2b771abc-0ab8-11e5-8a92-31be23fff63d.jpg)
