### ISSUE TITLE
If repo is enabled by one user, show it to others

### ISSUE THREAD

**Issue by amitaibu** [shoov/shoov#325]
This will prevent cases where people try to enable an already enabled group (which they are not members yet)

**Comment by HelenaEksler** [comment]
Should they have access to it as well?

**Comment by amitaibu** [comment]
For now no - access would be in follow up,  as we will have to sync the github access and the OG membership

**Comment by HelenaEksler** [comment]
Do it Angular? Or in ELM? I mean, showing that repository is enabled effects client, so in which should I make changes in this PR?

**Comment by amitaibu** [comment]
Currently we only have the Angular one.

**Comment by HelenaEksler** [comment]
ok
