### ISSUE TITLE
remove the og_ungroup from the sync code

### ISSUE THREAD

**Issue by amitaibu** [shoov/shoov#336]
Some people might login with public only access,  so we currently can't check their private repo membership

**Comment by HelenaEksler** [comment]
In this case I suppose they shouldn't see the private repositories, no?

**Comment by amitaibu** [comment]
it's a special case, so for now we can just remove the `og_ungroup()`. In the future we will hold the info if the user subscribed with public/ private - so we can be smarter about it.
