### ISSUE TITLE
Add bash script to add behat files and .shoov.yml to an existing repo

### ISSUE THREAD

**Issue by amitaibu** [shoov/shoov#34]
We should make it easier for people to connect their repo to the live monitor.

So a dev may execute `curl -s http://server/path/script.sh | bash http://my-site.com` from the root of their repo, and it will add a working `behat` directory and a `.shoov.yml`. The behat will be a simple test that asserts the URL returns a 200.

**Comment by amitaibu** [comment]
The script could:
1. git clone https://github.com/amitaibu/gizra-behat into `.shoov-temp`
2. copy `behat` and `.shoov.yml` into the root
3. Replace the URL in the `behat.local.yml.example` if one provided as the argument. Otherwise keep as is.

**Comment by solker** [comment]
``` bash
# Check we are inside a git repo, and in the root
# ...
git clone https://github.com/amitaibu/gizra-behat .shoov-temp
cd .shoov-temp
tar zxf behat-vendor.tar.gz
cp behat.local.yml.example behat.local.yml
...
```

**Comment by solker** [comment]
I got an error while trying to run behat test from the downloaded repository. 

![selection_082](https://cloud.githubusercontent.com/assets/10127295/8024152/0ea3e150-0d32-11e5-8d93-2059d9370a7f.png)

**Comment by solker** [comment]
What is the best way to share file (script) with public access on Drupal?
To get access for exmaple to this file http://shoov.local/path/script.sh

**Comment by solker** [comment]
Well we don't need unpack zip with Behat on the user side because shoovl.yml do this job in the docker. But then user can't test behat script himself. Or we need remove unpack commands from shoov file? 
If before_script commands are failed, main part of script will be executed?

**Comment by amitaibu** [comment]
You can unpack, so they can test it locally without needing to composer
install

**Comment by amitaibu** [comment]
> What is the best way to share file (script) with public access on Drupal?

We don't have to host the file on Drupal, this can be a file even on github
for now

**Comment by solker** [comment]
Closed because already merged to shoov.io.
