### ISSUE TITLE
Update modules to recent version

### ISSUE THREAD

**Issue by amitaibu** [shoov/shoov#341]
@HelenaEksler Seems recent PR didn't include all the modules that needed upgrading (`/admin/reports/updates`) - can you please include all of them

**Comment by HelenaEksler** [comment]
I've updated those that have security updates (this caused the red warning)

**Comment by amitaibu** [comment]
well, we shouldn't neglect the other ones as-well ;)

**Comment by amitaibu** [comment]
@HelenaEksler can you please try to run this on an existing dump, and call `dpm(shoov_pusher_get_pusher());` -- I believe `composer_manager` module upgrade is causing it to fail.

**Comment by amitaibu** [comment]
After update pusher seems to not be installed properly (`/admin/config/system/composer-manager`)

![composer_manager___shoov](https://cloud.githubusercontent.com/assets/125707/12179638/ad079cfa-b580-11e5-841a-07eebb41bd36.jpg)

**Comment by amitaibu** [comment]
Seems changing this setting was missing:

![composer_manager___shoov](https://cloud.githubusercontent.com/assets/125707/12179754/520c1d3e-b581-11e5-93ae-9b6d1fb22bbb.jpg)

**Comment by amitaibu** [comment]
(I'll just change it manually when deploying to Live)
