### ISSUE TITLE
Tasks re-queue multiple times

### ISSUE THREAD

**Issue by amitaibu** [shoov/shoov#357]
message ID 985926 reports wrong access to node 11292 - however it's the same user

**Comment by HelenaEksler** [comment]
@amitaibu For some reason user is not member of the group, but is member of the CI Build. To fix - run:

``` php
$params = array(
  'entity_type' => 'user',
  'entity' => user_load(154),
  'field_name' => 'og_user_node'
);
og_group('node', 11291, $params);
og_ungroup('node', 11292, 'user', 154);
```

Or can be changed in the database

``` sql
UPDATE `og_membership` SET `gid`=11291 WHERE `etid` = 154 AND `gid` = 11192
```

For further investigation - membership in the CI Build was created on Thu, 01 Oct 2015 00:04:46 GMT.

**Comment by amitaibu** [comment]
What do you mean by member of the ci build? Isn't ci build just a group
content?

**Comment by amitaibu** [comment]
Btw, a direct update of the db is a bad practice - as it skips the api
which is doing necessary validations.

**Comment by HelenaEksler** [comment]
in membership row in the Database for some reason ID of group is ID of the CI Build node, not repository ID

**Comment by HelenaEksler** [comment]
> Btw, a direct update of the db is a bad practice - as it skips the api
> which is doing necessary validations.

That's why I've also written the code that can be executed.

**Comment by amitaibu** [comment]
Can you try to investigate how it happened. Also need to find if there are
other similar  cases.

**Comment by HelenaEksler** [comment]
@amitaibu Sorry, I was wrong that CI Build is set as a group. Probably I messed up with IDs. The only problem is that user was ungrouped.

**Comment by amitaibu** [comment]
admin/content/re-queued-items
