### ISSUE TITLE
Shoov-badges site it's down

### ISSUE THREAD

**Issue by mldk-tech** [shoov/shoov#364]
http://shoov-badges.gizra.com/

![selection_006](https://cloud.githubusercontent.com/assets/5812423/15666822/93557234-271b-11e6-9115-1fe01518f20b.png)

GitHube status
![selection_007](https://cloud.githubusercontent.com/assets/5812423/15666867/bc315164-271b-11e6-9e9b-0a5bd5d81fb4.png)

**Comment by amitaibu** [comment]
@bricel can you fix the DNS please

**Comment by bricel** [comment]
Should work in 15'
