### ISSUE TITLE
Question on deploying Shoov in the cloud and setting up alerts

### ISSUE THREAD

**Issue by mccrodp** [shoov/shoov#369]
>Shoov visually detects issues as they rise and alerts your team.

Hey, I have a few questions about this to get a feel for how much customisation is required to avoid re-doing something that Shoov may already do.

- Is there any docs on this part, re: alerts, or where is the code for this?
- What methods are there to notify a team and if email only, does it use the email defined at app.shov.io or otherwise?
- Slack integration would be a great future addition :P *

* StatusOk provides this, but it seems to be just a monitoring tool, without the power of Shoov re: Visual Regression testing https://github.com/sanathp/statusok/tree/master/notify

**Comment by amitaibu** [comment]
> What methods are there to notify a team and if email only, does it use the email defined at app.shov.io or otherwise?

Currently there's only an email option - that one that we got from GitHub.

You can also get a badge with the status, so you can place it in your own custom dashboard
![https___app_shoov_io___repos_5371](https://cloud.githubusercontent.com/assets/125707/21802714/85d98ed2-d72f-11e6-8a46-a35e26c5d2bd.jpg)

**Comment by mccrodp** [comment]
Thanks @amitaibu. Where are the rules for email notifications defined?
i.e. - how does it know when to alert, on any errors found, or emailing a report regardless of fail / pass after each regression test completion.

So, in my case, it would use the email I define at this point, correct? https://github.com/mccrodp/shoov/blob/master/Dockerfile#L44

**Comment by amitaibu** [comment]
>  how does it know when to alert

Email is sent only for the `live monitor` - if there are 3 fails in a row. (and of course, you can wire your live monitor to run your visual regression). You get this once you scaffold with https://github.com/shoov/generator-shoov

> So, in my case, it would use the email I define at this point, correct? 

Not sure, you'll have to check :)

**Comment by mccrodp** [comment]
Great, thanks a lot, that answers my questions on that.

So, all controlled by the `app.shoov.io` backend, so I imagine it'll use the GitHub email defined there rather than the email linked to the repository I showed.

I'm a little confused about the architecture still, but think things are getting a little clearer. It says in the tutorial:

>you should be able to install and setup your own computer

Does that mean that to test a site, I don't need to install shoov somewhere? i.e.  `app.shoov.io` triggers tests via it's own copy of shoov (on your Google containers) and just points (to a repo) to the `shoov.xml` for behat monitoring tests and/or `shoov.json` and test definitions similar to that in the [example repo](https://github.com/shoov/test-example) for visual regression tests.

If app.shoov.io calls it's own version of shoov, I guess that means the work I have done in my [mccrodp/shoov](https://github.com/mccrodp/shoov) repo is somewhat redundant, unless I fork the backend to work with it.

I had intended to install shoov somewhere (e.g. some cloud Docker host) and periodically call the below to run my visual regression tests, but this maybe overkill considering the above.

````
PROVIDER_PREFIX=browserstack SELECTED_CAPS=chrome mocha
````

**Comment by mccrodp** [comment]
Ok, so I've gotten a bit further with my understanding. 

The "Live Monitor" needs access to a GitHub repository (with `.shoov.yml`) and it seems like it has access to the private ones via integrating my GitHub account, which is great.

The "Visual Regression" testing is as I thought previously, you must have Shoov running locally or on a server (even Docker container as is my goal) and kick off the regression testing from there.

I am a bit confused by 
>No builds were uploaded yet. Make sure you have created your ~/.shoov.json file by copy pasting the following code into your terminal

I have also forked the repo https://github.com/mccrodp/test-example, so I'm not exactly sure how to "upload builds" or if that's something I need to do or not to get some kind of visual cue in the "Visual Regression" tab https://app.shoov.io/#/builds.

**Comment by mccrodp** [comment]
I have an understanding of the architecture now, so from my understanding:

Everything is controlled via `app.shoov.io` backend, the tutorials just explain how you would go about running things locally, but the backend takes care of a lot of this in practive, such as resolving the `.shoov.json` (as you don't commit this to your repo).

You just point the "Live Monitor" in the backend to your repo (with `.shoov.yml`) on "master" branch and both the behat tests for monitoring and the visual regression tests can be called from there. Then builds only show in Visual Regression UI if a problem is found, you don't need to look at builds there otherwise.
