### ISSUE TITLE
Shoov seems only finds .shoov.xml if master branch exists

### ISSUE THREAD

**Issue by mccrodp** [shoov/shoov#372]
In the `app.shoov.io` interface "Live Monitoring" tab, it only finds and allows use with a repo that has a `master` branch. We only had a `develop` branch, we don't usually have a master branch, and it was giving error below :

>No .shoov.yml file.

Is this easy to allow use with whatever default branch is? Otherwise, it might be worth noting.

Thanks.

**Comment by amitaibu** [comment]
There's no hardcoding to the branch name. You can set it on the `CI build`

![edit_ci_build_mccrodp_x-team-dot-com-monitor___shoov](https://cloud.githubusercontent.com/assets/125707/21848624/11b3bc48-d802-11e6-8e8b-68b2a5e7b5e4.jpg)

**Comment by amitaibu** [comment]
@mccrodp btw, maybe we'll get to discuss this in person in DrupalCamp Tokyo?:)

**Comment by mccrodp** [comment]
@amitaibu - thanks a lot, looks nice and easy. If only I knew where "CI build" tab was, not sure if it's Shoov specific or GitHub after having a look around.

I saw you were giving a talk on Elm at it, would love to be at that. Not moving there until March, so bad timing for me :) Good luck with it!

btw, got Live Monitor working on a repo and saw some failing builds for another repo on Visual Regression tab. So I'm getting there with it and it's looking really promising, great work 👍 . Going to open a ticket with Saucelabs re: https://github.com/shoov/shoov/issues/371

**Comment by amitaibu** [comment]
`CI build` is a node type that is created when you enable a live monitor.

**Comment by mccrodp** [comment]
Do I have access to that node type via the `app.shoov.io` backend? All I see is the below.

![shoov-monitor-xteam](https://cloud.githubusercontent.com/assets/559938/21849101/fa9ad0b0-d7fb-11e6-85ef-b9fc3a3fa056.png)

**Comment by amitaibu** [comment]
no, you don't. But if you want I could change it manually for you

**Comment by mccrodp** [comment]
No, that's fine @amitaibu, let's leave it at `master` for now, just trying to get a picture of how it all fits together. Thanks again for your time!
