### ISSUE TITLE
No email alert notification received upon failure

### ISSUE THREAD

**Issue by mccrodp** [shoov/shoov#373]
Hi there,

I cloned our site and got tests passing on it, took the site down to verify a positive failure, and hooray, "Error" as seen below. However, I never received an email alert. Is it possible to verify why this might be and where / when the email notification was sent?

![build-failed-success](https://cloud.githubusercontent.com/assets/559938/21975898/2a482956-dbc7-11e6-820c-4e11adf621ee.png)

I created a follow up issue: https://github.com/shoov/shoov/issues/374 to this about rolling out Slack integration :)

**Comment by amitaibu** [comment]
Email alert is sent only after you get 3 errors in a row, to prevent false positives.

**Comment by mccrodp** [comment]
Ahhh, just 1 more red Error...

Will re-test, thanks!

**Comment by mccrodp** [comment]
It works!!! :) Now onto Slack integration.
