### ISSUE TITLE
Update modules to latest release

### ISSUE THREAD

**Issue by amitaibu** [shoov/shoov#38]
`admin/reports/updates/update`

![available_updates___shoov](https://cloud.githubusercontent.com/assets/125707/8022864/f2832944-0cf6-11e5-9a8a-144d5d75a2c0.jpg)

Don't update OG and Migrate for now.

**Comment by solker** [comment]
For me it's not working ^^
But I still receive notification about secure updates.
![selection_081](https://cloud.githubusercontent.com/assets/10127295/8023752/450af532-0d21-11e5-8881-9732ddd53317.png)

**Comment by amitaibu** [comment]
Anyway, you need to update the make file.
