### ISSUE TITLE
Uncaught Error: Cannot find module 'webdriverio'

### ISSUE THREAD

**Issue by mldk-tech** [shoov/shoov#42]
Please add to the package.json file in the  dependencies the webdriverio module.

`"webdriverio": "^2.4.5"`

![sssssssss](https://cloud.githubusercontent.com/assets/5812423/8023168/6f522906-0d07-11e5-9de5-e7be8fc79f96.png)

**Comment by amitaibu** [comment]
Seems your shoov code is outdated.
