### ISSUE TITLE
I do not see the new image regression in my shoov account after the test.

### ISSUE THREAD

**Issue by mldk-tech** [shoov/shoov#43]
1. I see in my terminal that i have a regression but when i going to my account in shoov i do not see the regression.
2. The link in the end of the test that need to take me to the page that show me the regression take me to this page when i login.

![selection_003](https://cloud.githubusercontent.com/assets/5812423/8023207/3f84525c-0d08-11e5-928a-2d9d18f2d2ac.png)

**Comment by amitaibu** [comment]
Seems your shoov code is outdated.
