### ISSUE TITLE
JS error when trying to create a pull request

### ISSUE THREAD

**Issue by klamping** [shoov/shoov#55]
When try creating a pull request using the interface:
![screen shot 2015-06-09 at 3 21 34 pm](https://cloud.githubusercontent.com/assets/706039/8068731/5ce57592-0ebb-11e5-9ec4-c4cf80059255.png)

It errors out with:
![image](https://cloud.githubusercontent.com/assets/706039/8068505/d933e66c-0eb9-11e5-8def-b9a749f76407.png)

**Comment by amitaibu** [comment]
@klamping indeed, known issue -- the Create PR button still requires you to hit f5 after a few seconds.

We should fix the JS, but also plan to integrate with pusher.com to get real time notification when PR is ready.

**Comment by klamping** [comment]
Ah, that's what that text was about. Makes more sense now.

**Comment by amitaibu** [comment]
#57.

Anyway, you should still be able to create a PR, or download the images you want.

**Comment by amitaibu** [comment]
@HelenaEksler please tackle this -- and add Pusher integration, so whenever the status changes, the link is updated.
