### ISSUE TITLE
Incorrect token in .shoov.json file.

### ISSUE THREAD

**Issue by solker** [shoov/shoov#69]
When i first time try to get `.shoov.json` for visual regression i got incorrect access token.
![selection_105](https://cloud.githubusercontent.com/assets/10127295/8300784/092835ee-1991-11e5-97d0-61f203468c26.png)
![selection_106](https://cloud.githubusercontent.com/assets/10127295/8300787/0be6e3b6-1991-11e5-86fd-4fd95ffa6745.png)

**Comment by solker** [comment]
Hm, also if i download token by curl and by browser i got different results.
![selection_108](https://cloud.githubusercontent.com/assets/10127295/8300836/a46c661a-1991-11e5-99d4-bfe7c0e8fe38.png)
![selection_107](https://cloud.githubusercontent.com/assets/10127295/8300839/aaccefca-1991-11e5-8330-fa7d804ceca8.png)

It's looking like if i use curl i get access token from the url.

**Comment by amitaibu** [comment]
might be related to first time - so token is just created.

Probably coming from [this](https://github.com/shoov/shoov/blob/master/shoov/modules/custom/shoov_restful/plugins/restful/user/config/1.0/ShoovConfigResource.class.php#L58) area
