### ISSUE TITLE
On unconfirmed error send request to 2nd nodejs server

### ISSUE THREAD

**Issue by amitaibu** [shoov/shoov#99]
- Currently we have `shoov_ui_build_pr_server` please rename it to `shoov_nodejs_server`
- Add another `shoov_nodejs_server_secondary` that when we have unconfirmed error, we will use that as the [base url](https://github.com/shoov/shoov/blob/master/shoov/modules/custom/shoov_ci_build/drush/shoov_ci_build.drush.inc#L38) (e.g. `shoov_ci_build_get_nodejs_server_url()`)
- Add docs in the README about the variables.

**Comment by solker** [comment]
Please update the README.

> Add docs in the README about the variables.
